development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://fayeserverskillswap.herokuapp.com/"
  secret_token: ENV['FAYE_TOKEN']
  signature_expiration: 3600 # one hour
